### ISSUE TITLE
YoutubeException$VideoUnavailableException: Could not load url

### ISSUE THREAD

**Issue by Zenqrt** [sealedtx/java-youtube-downloader#27]
It says that it can't load the URL and I don't know why. I checked the link is the video id is everything seems fine. 

Error:
`Exception in thread "main" com.github.kiulian.downloader.YoutubeException$VideoUnavailableException: Could not load url: https://www.youtube.com/watch?v=byUCOO2qm_A
	at com.github.kiulian.downloader.extractor.DefaultExtractor.loadUrl(DefaultExtractor.java:97)
	at com.github.kiulian.downloader.parser.DefaultParser.getPlayerConfig(DefaultParser.java:66)
	at com.github.kiulian.downloader.YoutubeDownloader.getVideo(YoutubeDownloader.java:65)
	at main.AnotherMAin.main(AnotherMAin.java:27)`

Code:
`YoutubeDownloader downloader = new YoutubeDownloader();

        Scanner scanner = new Scanner(System.in);

        String videoId = scanner.nextLine().replace("https://www.youtube.com/watch?v=", "").replace("https://youtu.be/", "");

        System.out.println("videoId = " + videoId);
        YoutubeVideo video = downloader.getVideo(videoId); // LINE WITH ERROR
        List<AudioVideoFormat> videoWithAudioFormats = video.videoWithAudioFormats();
        videoWithAudioFormats.forEach(it -> {
            System.out.println(it.videoQuality() + " : " + it.url());
        });
        video.downloadAsync(videoWithAudioFormats.get(0), new File("D:\\Game Projects\\orihS Bot Project\\target\\classes\\songs\\ACertainMagicalIndexIII"), new OnYoutubeDownloadListener() {
            @Override
            public void onDownloading(int progress) {
                System.out.printf("Downloaded %d%%\n", progress);
            }

            @Override
            public void onFinished(File file) {
                System.out.println("Finished file: " + file);
                try {
                    main(null);
                } catch (IOException | YoutubeException e) {
                    e.printStackTrace();
                }
            }

            @Override
            public void onError(Throwable throwable) {
                System.out.println("Error: " + throwable.getLocalizedMessage());
            }
        });`

**Comment by sealedtx** [comment]
@Zenqrt Hi! I just tested your videoId and everything seems ok. Basically `YoutubeException$VideoUnavailableException` exception is thrown when `DefaultExtractor#loadUrl` fails to load html page - because `IOException`  exception is thrown during connection/downloading. Later I may try to add more detailed message not just "Could not load url".  Have a look at this implementation:
https://github.com/sealedtx/java-youtube-downloader/blob/57179f9766d05d873f9ff874b299c24509d14190/src/main/java/com/github/kiulian/downloader/extractor/DefaultExtractor.java#L74-L98

Is this error appears only for this video, or for all? Possible reasons could be network errors (e.g. youtube can send 429 if you spam requests), network configurations, firewall, etc, everything which can block HttpURLConnection successfull work.

I have omitted printing IOException stacktrace at line 94, because didn't want to flood to stderr each download retry, you may copy `loadUrl` implementation to simple test and add printing stacktrace to undestand what exactly exception is thrown.

Feel free to add more details and ask questions.

**Comment by Zenqrt** [comment]
Thanks! It is most likely 429 error because I tried playing songs from YouTube on a Discord Bot but all I got were 429 errors.
