### ISSUE TITLE
Download an entire channel?

### ISSUE THREAD

**Issue by Fabulierer** [sealedtx/java-youtube-downloader#70]
Is there a way of downloading an entire channel like it was a playlist? Would be great for my project. Love your work btw!

**Comment by sealedtx** [comment]
@Fabulierer Hi, I like your feature request, but it requires lot of research. Unfortunately I have no free time to do it right now. To help your may: 
- try searching similar solutions like 'youtube-dl'; it will be easier to convert existing code rather than writing from scratch. 
- submit pull request
Thank you.
